#!/usr/bin/env python3
"""
Smart Contract Deployer — SecurityRegistry.sol
Deploys the contract to Ganache and outputs the address for .env

Usage:
    python3 smart_contracts/deploy.py

Prerequisites:
    1. Ganache running:  ganache-cli --port 7545 --networkId 1337 --deterministic
    2. solc installed:   npm install -g solc   OR  pip install py-solc-x
    3. .env has:         BLOCKCHAIN_URL=http://<ganache-ip>:7545
"""
import os
import sys
import json

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    from web3 import Web3
except ImportError:
    print("❌ web3 not installed — run: pip install web3>=6.0.0")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────
BLOCKCHAIN_URL = os.getenv("BLOCKCHAIN_URL", "http://127.0.0.1:7545")
SOL_FILE       = os.path.join(os.path.dirname(os.path.abspath(__file__)), "SecurityRegistry.sol")
ABI_FILE       = os.path.join(os.path.dirname(os.path.abspath(__file__)), "SecurityRegistry_abi.json")
BIN_FILE       = os.path.join(os.path.dirname(os.path.abspath(__file__)), "SecurityRegistry_bin.txt")
ENV_FILE       = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")

print("\n" + "=" * 60)
print("⛓️   SecurityRegistry Contract Deployer")
print("=" * 60)
print(f"   Blockchain : {BLOCKCHAIN_URL}")
print(f"   Contract   : {SOL_FILE}\n")

# ── Connect ───────────────────────────────────────────────────────────
w3 = Web3(Web3.HTTPProvider(BLOCKCHAIN_URL))
if not w3.is_connected():
    print(f"❌ Cannot connect to blockchain at {BLOCKCHAIN_URL}")
    print("   Start Ganache:  ganache-cli --port 7545 --networkId 1337 --deterministic")
    sys.exit(1)

print(f"✅ Connected — Chain ID: {w3.eth.chain_id}")
print(f"   Accounts   : {len(w3.eth.accounts)} available")
deployer = w3.eth.accounts[0]
balance  = w3.from_wei(w3.eth.get_balance(deployer), "ether")
print(f"   Deployer   : {deployer}")
print(f"   Balance    : {balance} ETH\n")

# ── Compile ABI/BIN ───────────────────────────────────────────────────
# First try pre-compiled files (generated by solc or Remix)
if os.path.exists(ABI_FILE) and os.path.exists(BIN_FILE):
    print(f"✅ Using pre-compiled ABI/BIN from:")
    print(f"   {ABI_FILE}")
    print(f"   {BIN_FILE}")
    with open(ABI_FILE, "r") as f:
        abi = json.load(f)
    with open(BIN_FILE, "r") as f:
        bytecode = f.read().strip()

else:
    # Try py-solc-x for automatic compilation
    print("⚠️  No pre-compiled ABI/BIN found — attempting auto-compile with py-solc-x…")
    try:
        from solcx import compile_source, install_solc
        install_solc("0.8.19", show_progress=True)

        with open(SOL_FILE, "r") as f:
            source = f.read()

        compiled = compile_source(
            source,
            output_values=["abi", "bin"],
            solc_version="0.8.19",
        )
        key      = [k for k in compiled.keys() if "SecurityRegistry" in k][0]
        abi      = compiled[key]["abi"]
        bytecode = compiled[key]["bin"]

        # Save compiled files for next time
        with open(ABI_FILE, "w") as f:
            json.dump(abi, f, indent=2)
        with open(BIN_FILE, "w") as f:
            f.write(bytecode)
        print(f"✅ Compiled and cached → {ABI_FILE}")

    except ImportError:
        print("❌ py-solc-x not installed and no pre-compiled files found.")
        print("\nOption A (easiest): Compile in Remix IDE (remix.ethereum.org)")
        print("   1. Paste SecurityRegistry.sol content")
        print("   2. Compile with 0.8.19")
        print("   3. Copy ABI → smart_contracts/SecurityRegistry_abi.json")
        print("   4. Copy Bytecode (not deployedBytecode) → smart_contracts/SecurityRegistry_bin.txt")
        print("   5. Re-run this script")
        print("\nOption B: pip install py-solc-x")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Compilation failed: {e}")
        sys.exit(1)

# ── Deploy ────────────────────────────────────────────────────────────
print("\n🚀 Deploying SecurityRegistry…")
Contract = w3.eth.contract(abi=abi, bytecode=bytecode)
tx_hash  = Contract.constructor().transact({"from": deployer, "gas": 3_000_000})
receipt  = w3.eth.wait_for_transaction_receipt(tx_hash)
addr     = receipt.contractAddress

print(f"\n✅ Contract deployed successfully!")
print(f"   Address    : {addr}")
print(f"   Tx hash    : {tx_hash.hex()}")
print(f"   Block      : {receipt.blockNumber}")
print(f"   Gas used   : {receipt.gasUsed:,}")

# ── Update .env ───────────────────────────────────────────────────────
if os.path.exists(ENV_FILE):
    with open(ENV_FILE, "r") as f:
        env_content = f.read()

    if "CONTRACT_ADDRESS=" in env_content:
        lines = env_content.splitlines()
        updated = []
        for line in lines:
            if line.startswith("CONTRACT_ADDRESS="):
                updated.append(f"CONTRACT_ADDRESS={addr}")
            else:
                updated.append(line)
        env_content = "\n".join(updated) + "\n"
    else:
        env_content += f"\nCONTRACT_ADDRESS={addr}\n"

    with open(ENV_FILE, "w") as f:
        f.write(env_content)
    print(f"\n✅ .env updated with CONTRACT_ADDRESS={addr}")
else:
    print(f"\n📋 Add this to your .env file:")
    print(f"   CONTRACT_ADDRESS={addr}")

print("\n📋 Next steps:")
print("  1. Restart pi_backend/blockchain_bridge.py")
print(f"  2. Register RFID: curl -X POST http://localhost:5010/register_rfid \\")
print(f"       -H 'Content-Type: application/json' \\")
print(f"       -d '{{\"uid\": \"YOUR_CARD_UID\", \"owner\": \"Mridul\"}}'")
